name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
  workflow_dispatch:
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    strategy:
      matrix:
        proj: [VRDR, VRDR.Messaging, VRDR.Client]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      # Publish
      - name: publish on version change
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: ${{ matrix.proj }}/${{ matrix.proj }}.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, shared between all projects in this repo
          VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          TAG_COMMIT: true # Tag the project when the version has changed
          TAG_FORMAT: ${{ matrix.proj }}-v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
          PACKAGE_NAME: ${{ matrix.proj }}
          INCLUDE_SYMBOLS: false