name: Increment project version
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.project-filter.outputs.projects }}
      subject: ${{ steps.commit-subject.outputs.subject }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 2
      - name: Filter list of changed projects
        id: project-filter
        run: |
          echo "projects=$(git diff-tree HEAD | awk '$1$2~/04/' | cut -f2- | grep -e ^VRDR$ -e ^VRDR.Client$ -e ^VRDR.CLI$ | jq -cnR '[inputs | select(length>0)]')" >> "$GITHUB_OUTPUT"
      - name: Get commit subject
        id: commit-subject
        run: |
          echo "subject=$(git log -n 1 --pretty=%s)" >> $GITHUB_OUTPUT
  versionize:
    runs-on: ubuntu-latest
    needs: query
    if: "${{ !startsWith(needs.query.outputs.subject, 'build: bump ') }}"
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.query.outputs.projects) }}
    steps:
      - run: echo ${{ matrix.project }}
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Setup Versionize
        run: |
          dotnet tool install --global Versionize
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Bump version and create changelog
        working-directory: ./${{ matrix.project }}
        run: |
          versionize --proj-version-bump-logic --skip-tag --changelog-all
      - name: Get current version
        id: get-version
        working-directory: ./${{ matrix.project }}
        run: |
          echo "version=$(versionize inspect)" >> $GITHUB_OUTPUT
      - name: Create release Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: ${{ secrets.WHICHWIT_BOT_TOKEN }}
          commit-message: |
            build: bump ${{ matrix.project }} to ${{ steps.get-version.outputs.version }}
          title: |
            build: bump ${{ matrix.project }} to ${{ steps.get-version.outputs.version }}
          body: ""
          branch: versionize-${{ matrix.project }}
          reviewers: ${{ github.actor }}
          delete-branch: true